### ISSUE TITLE
ALOS-2 yaml

### ISSUE THREAD

**Issue by matthewsteventon** [opendatacube/datacube-core#470]
Writing to see if you might be able to help us with a VNDC related issue please.

RESTEC are having some issues around the choice of data types in the following files. The following are the files used by Vietnam to ingest their ALOS-2 data.

https://github.com/vndatacube/odc-config-files/blob/master/alos/alos2_tile_productdef.yaml

https://github.com/vndatacube/odc-config-files/blob/master/alos/alos2_tile_wgs84_50m.yaml

Okumura-san has confirmed that the data types used here match the data definition. With that said, when the RESTEC team try to run their Python notebook, the `dc.load` step produces the following error for the incidence angle and mask products:

`TypeError: Cannot cast scalar from dtype('float32') to dtype('uint8') according to the rule 'same_kind'`

FYI they are running Python3.5. 

They are able to work around the issue. Two work arounds exist: using int8 (issues with negative values, but this can be further worked around) or using int16 (works without errors, but uses more resources). 

To get this notebook running, there are three options that we see:

1. Implement a work around – but this is not ideal as it would have to be done in every application/uses more resources (for int16 case).
2. Change the VN Cube yamls and reingest all of the VNCube data using the data types that work. They would however prefer to not change these values, as they are consistent with the data definition. Also wish to avoid reingesting all the data. 
3. Edit the `load()` function to manage the data types correctly. They would need assistance from core developers to do this.

Are you able to advise please? Let me know if you need any more info.

Many thanks in advance.

**Comment by omad** [comment]
Thanks for the report, this is something that should work, but the interplay of `numpy`/`gdal`/`rasterio`/`NetCDF(+CF)` can make the managing of `dtypes` a bit messy. None of the Geoscience Australia data uses `uint8`, but the CF-Mask for USGS Landsat does, so this shouldn't be completely new ground.

It sounds like a problem with `ingested` data. It should be possible to `dc.load()` directly from the uningested data, which may be a useful work around. I wouldn't necessarily recommend `ingesting` to NetCDF unless it is proved to improve performance in a particular deployment.

For reference:
[NetCDF CF Conventions DataTypes](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_data_typesl)
[Rasterio DataTypes](https://github.com/mapbox/rasterio/blob/master/rasterio/dtypes.py)

**Comment by Kirill888** [comment]
@matthewsteventon can you run `ncdump -hs <path/to/ingested/file.nc>` and post the result here. By the looks of it some arrays got stored as `float32` by ingestor. Ingestor should probably refuse to process product definitions that are not compatible with NetCDF CF format, i.e. any product that includes unsigned integer types, and not silently change data type on disk without changing product definition, which I suspect is what's happening here.

In general when choosing types for ingested products: pick smallest signed integer type that will hold your unsigned value, sorry that's netcdf cf constraint.

**Comment by felipk101** [comment]
@Kirill888 I tried to recreate the error with the same config parameters as in the supplied config files. Generated a uint8 geotiff and ingested it. I wasn't able to recreate this error. uint8 ingested and loaded successfully so not a generic uint8 error and likely to be dataset specific.
![uint8](https://user-images.githubusercontent.com/5178605/40763282-ce1b254c-64e7-11e8-922e-fe95109a418b.png)

**Comment by Kirill888** [comment]
@felipk101 can you repeat the same without reprojection? Omit output_crs and resolution parameters.

also can you run ncdump on one of the ingested files

**Comment by felipk101** [comment]
@Kirill888 see below for ncdump of the netcdf header.

```
netcdf ALOS2_PALSAR2_4326_50m_-4_79_20170430140716518085 {
dimensions:
        time = 1 ;
        latitude = 2213 ;
        longitude = 2129 ;
        dataset_nchar = 2672 ;
variables:
        double time(time) ;
                time:units = "seconds since 1970-01-01 00:00:00" ;
                time:standard_name = "time" ;
                time:long_name = "Time, unix time-stamp" ;
                time:axis = "T" ;
                time:calendar = "standard" ;
        double latitude(latitude) ;
                latitude:units = "degrees_north" ;
                latitude:standard_name = "latitude" ;
                latitude:long_name = "latitude" ;
                latitude:axis = "Y" ;
        double longitude(longitude) ;
                longitude:units = "degrees_east" ;
                longitude:standard_name = "longitude" ;
                longitude:long_name = "longitude" ;
                longitude:axis = "X" ;
        int crs ;
                crs:long_name = "WGS 84" ;
                crs:grid_mapping_name = "latitude_longitude" ;
                crs:longitude_of_prime_meridian = 0. ;
                crs:semi_major_axis = 6378137. ;
                crs:semi_minor_axis = 6356752.31424518 ;
                crs:inverse_flattening = 298.257223563 ;
                crs:crs_wkt = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" ;
                crs:spatial_ref = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" ;
                crs:GeoTransform = -4., 0.000469546, 0., 80., 0., -0.000451796999999999 ;
        ubyte incidence_angle(time, latitude, longitude) ;
                incidence_angle:_FillValue = 1UB ;
                incidence_angle:grid_mapping = "crs" ;
                incidence_angle:units = "1" ;
        char dataset(time, dataset_nchar) ;

// global attributes:
                :date_created = "2018-05-31T05:14:49.041396" ;
                :Conventions = "CF-1.6, ACDD-1.3" ;
                :history = "This data represents a tile and reprojection of ALOS-2 PALSAR-2 data." ;
                :geospatial_bounds = "POLYGON ((-4 80,-4.0 79.000173239,-3.000336566 79.000173239,-3.000336566 80.0,-4 80))" ;
                :geospatial_bounds_crs = "EPSG:4326" ;
                :geospatial_lat_min = 79.000173239 ;
                :geospatial_lat_max = 80. ;
                :geospatial_lat_units = "degrees_north" ;
                :geospatial_lon_min = -4. ;
                :geospatial_lon_max = -3.000336566 ;
                :geospatial_lon_units = "degrees_east" ;
                :title = "Vietnam Data Cube ALOS-2 PALSAR-2 Gamma0" ;
                :summary = "ALOS-2 PALSAR-2 data derived from JJ-FAST ScanSAR data." ;
                :institution = "JAXA" ;
                :instrument = "PALSAR-2" ;
                :cdm_data_type = "Grid" ;
                :keywords = "VN/VNSC,ALOS-2,PALSAR-2,JAXA,RESTEC,EARTH SCIENCE" ;
                :keywords_vocabulary = "GCMD" ;
                :platform = "ALOS-2" ;
                :processing_level = "L2" ;
                :product_version = "1.0.0" ;
                :product_suite = "ALOS-2" ;
                :project = "Vietnam Data Cube" ;
                :publisher_email = "datacube@vnsc.org.vn" ;
                :publisher_name = "Vietnam Data Cube" ;
                :publisher_url = "www.vnsc.org.vn" ;
                :coverage_content_type = "physicalMeasurement" ;
                :license = "https://creativecommons.org/licenses/by/4.0/" ;
                :naming_authority = "vn.org.vnsc" ;
                :acknowledgment = "ALOS-2 data is provided by JAXA and RESTEC" ;
}
```

**Comment by felipk101** [comment]
It's correctly mapped to ubyte.

I would go with Damien's suggestion and try the datacube.load on the dataset rather then ingest since this is an alos2 yearly produced mosaic so likely to be a single slice in time there won't be any performance gain to ingest.

**Comment by felipk101** [comment]
Also, unable to omit CRS and Resolution as data product has no default CRS.
ValueError: Product has no default CRS. Must specify 'output_crs' and 'resolution'

When specifying EPSG:4326 and resolution loads as expected.

**Comment by Kirill888** [comment]
@felipk101 thanks, but ingested product must have gridspec, that's the whole point of that process, are reading from the ingested product?

@matthewsteventon I agree for your use-case ingestion is not necessary. But if you can provide us with full stack trace of the error might help up reproduce here.

**Comment by felipk101** [comment]
@Kirill888 

Error opening source dataset: NetCDF:/notebooks/ingested_Data/ALOS2_PALSAR2_4326_50m_-4_80_20170430140716518085.nc:incidence_angle

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-972fc944de82> in <module>()
----> 1 ds = dc.load(product='alos2_tile_50m_vietnam')

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in load(self, product, measurements, output_crs, resolution, resampling, stack, dask_chunks, like, fuse_func, align, datasets, use_threads, **query)
    317                                 fuse_func=fuse_func,
    318                                 dask_chunks=dask_chunks,
--> 319                                 use_threads=use_threads)
    320         if not stack:
    321             return result

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in load_data(sources, geobox, measurements, fuse_func, dask_chunks, skip_broken_datasets, use_threads)
    544 
    545         return Datacube.create_storage(OrderedDict((dim, sources.coords[dim]) for dim in sources.dims),
--> 546                                        geobox, measurements, data_func, use_threads)
    547 
    548     @staticmethod

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in create_storage(coords, geobox, measurements, data_func, use_threads)
    450             results = pool.map(work_measurements, measurements, repeat(data_func))
    451         else:
--> 452             results = [data_func(a) for a in measurements]
    453 
    454         for measurement in measurements:

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in <listcomp>(.0)
    450             results = pool.map(work_measurements, measurements, repeat(data_func))
    451         else:
--> 452             results = [data_func(a) for a in measurements]
    453 
    454         for measurement in measurements:

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in data_func(measurement)
    520                     for index, datasets in numpy.ndenumerate(sources.values):
    521                         _fuse_measurement(data[index], datasets, geobox, measurement, fuse_func=fuse_func,
--> 522                                           skip_broken_datasets=skip_broken_datasets)
    523                 else:
    524                     def work_load_data(array_name, index, datasets):

/usr/local/lib/python3.6/dist-packages/datacube/api/core.py in _fuse_measurement(dest, datasets, geobox, measurement, skip_broken_datasets, fuse_func)
    649                        resampling=measurement.get('resampling_method', 'nearest'),
    650                        fuse_func=fuse_func,
--> 651                        skip_broken_datasets=skip_broken_datasets)
    652 
    653 

/usr/local/lib/python3.6/dist-packages/datacube/storage/storage.py in reproject_and_fuse(datasources, destination, dst_transform, dst_projection, dst_nodata, resampling, fuse_func, skip_broken_datasets)
    213         for source in datasources:
    214             with ignore_exceptions_if(skip_broken_datasets):
--> 215                 read_from_source(source, buffer_, dst_transform, dst_nodata, dst_projection, resampling)
    216                 fuse_func(destination, buffer_)
    217 

/usr/local/lib/python3.6/dist-packages/datacube/storage/storage.py in read_from_source(source, dest, dst_transform, dst_nodata, dst_projection, resampling)
    164                 return
    165             dest = dest[offset[0]:offset[0] + tmp.shape[0], offset[1]:offset[1] + tmp.shape[1]]
--> 166             numpy.copyto(dest, tmp, where=(tmp != src.nodata))
    167         else:
    168             if dest.dtype == numpy.dtype('int8'):

TypeError: Cannot cast scalar from dtype('float32') to dtype('uint8') according to the rule 'same_kind'
```

**Comment by felipk101** [comment]
I was going straight to the dataset. Well pointed out. At least we know that not ingesting but going to the dataset is work around.

**Comment by Kirill888** [comment]
thanks @felipk101, looks like maybe `nodata` related?

**Comment by mi2koi4** [comment]
Thank you very much every one.  Here in RESTEC,  I got the same error message as following as @matthewsteventon -san kindly wrote.

```
...
~/Datacube/agdc-v2/datacube/storage/storage.py in read_from_source(source, dest, dst_transform, dst_nodata, dst_projection, resampling)
    151                 return
    152             dest = dest[offset[0]:offset[0] + tmp.shape[0], offset[1]:offset[1] + tmp.shape[1]]
--> 153             numpy.copyto(dest, tmp, where=(tmp != src.nodata))
    154         else:
    155             if dest.dtype == numpy.dtype('int8'):

TypeError: Cannot cast scalar from dtype('float32') to dtype('uint8') according to the rule 'same_kind'

```

Internal redmine at that time says "I could not figure out why tmp.dtype=float32 .."
```
ipdb> p tmp
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)
```

And, it seems I gave up after the following attempt in March 

```
tmp, offset, _ = _read_decimated(array_transform, src, dest.shape)

ipdb> p array_transform
Affine(0.9999999999999971, 0.0, -1943.0912306781684,
       0.0, 0.9999999999999991, -18.01991159746467)
ipdb> p src
<datacube.storage.storage.BandDataSource object at 0x7f14be9e07b8>
ipdb> p src.dtype
dtype('float32')
ipdb> q
...
...
### NOT A SOLUTION!!
/home/datacube_devel/Datacube/agdc-v2/datacube/storage/storage.py
line 153
-     numpy.copyto(dest, tmp, where=(tmp != src.nodata))
+     numpy.copyto(dest, tmp, casting='unsafe', where=(tmp != src.nodata))
```

**Comment by felipk101** [comment]
@Kirill888 not a nodata issue, quite sure it's coming from rasterio checking GDAL netcdf driver.

![rasterio](https://user-images.githubusercontent.com/5178605/40824847-022b2356-65b9-11e8-86ed-9f0363c9d85a.png)

**Comment by Kirill888** [comment]
Yeah looks like `rasterio` coercing to `float32`, do you want to raise issue at rasterio github for that @felipk101? What version of `rasterio/gdal` is this?

**Comment by felipk101** [comment]
rasterio is version 1.0a12 and gdal is 2.3.0

When opening netCDF4 not getting the error.
Will make raise an issue with rasterio.

**Comment by alexgleith** [comment]
Hey @mi2koi4

How is this issue going,  are you comfortable with the work around of going straight to the indexed data?

**Comment by felipk101** [comment]
Looks like this has been fixed in version  Rasterio 1.0b2
https://github.com/mapbox/rasterio/issues/1380#issuecomment-398785813

**Comment by mi2koi4** [comment]
Sorry for the late response.  I overlooked @alexgleith 's message after an long flight ... 
Now I have read the thread @felipk101 kindly pointed. Thank you very much! The best scenario for us is the improvement of Rasterio 1.0b2  will resolve this issue, which seems possible. (Meanwhile, we had a discussion about the possibility to re-think ALOS-2 data format (for example, to the same one as Sentinel-1), but now I think it will be not necessary)

**Comment by alexgleith** [comment]
Hey @mi2koi4, it seems that the issue is not solved yet. The RasterIO devs have acknowledged the issue, and say it will be fixed soon. I'll keep an eye on it!

**Comment by mi2koi4** [comment]
@alexgleith  Thank you again, understood.  I will also watch the issue in Rasterio !

**Comment by omad** [comment]
Seems like this is resolved now. Please re-open if it's still an issue. :)

**Comment by mi2koi4** [comment]
Thank you very much
